// This source code was generated by anyexec2c.
// Link: https://github.com/exyi/anyexec2C

{% for (filename, content) in comment_files %}
// ==============================
// {{ filename }}
// ==============================
// 
{% for line in content %}// {{ line }}
{% endfor %}


{% endfor %}

#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>

static char encoding_table[] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
'w', 'x', 'y', 'z', '0', '1', '2', '3',
'4', '5', '6', '7', '8', '9', '+', '/'};
static char *decoding_table = NULL;
static int mod_table[] = {0, 2, 1};

void build_decoding_table() {

decoding_table = (char*) malloc(256);

for (int i = 0; i < 64; i++)
decoding_table[(unsigned char) encoding_table[i]] = i;
}


unsigned char *base64_decode(const char *data,
size_t input_length,
size_t *output_length) {

if (decoding_table == NULL) build_decoding_table();

if (input_length % 4 != 0) return NULL;

*output_length = input_length / 4 * 3;
if (data[input_length - 1] == '=') (*output_length)--;
if (data[input_length - 2] == '=') (*output_length)--;

unsigned char *decoded_data = (unsigned char*) malloc(*output_length);
if (decoded_data == NULL) return NULL;

for (int i = 0, j = 0; i < input_length;) {

uint32_t sextet_a = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
uint32_t sextet_b = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
uint32_t sextet_c = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
uint32_t sextet_d = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];

uint32_t triple = (sextet_a << 3 * 6)
+ (sextet_b << 2 * 6)
+ (sextet_c << 1 * 6)
+ (sextet_d << 0 * 6);

if (j < *output_length) decoded_data[j++] = (triple >> 2 * 8) & 0xFF;
if (j < *output_length) decoded_data[j++] = (triple >> 1 * 8) & 0xFF;
if (j < *output_length) decoded_data[j++] = (triple >> 0 * 8) & 0xFF;
}

return decoded_data;
}

void extract(char* payload, const char* filename) {
	size_t len = 0;
	unsigned char* binary = base64_decode(payload, strlen(payload), &len);

	FILE *fp = fopen(filename ,"w");
	if (fp == NULL) {
		exit(33);
	}
	if (fwrite(binary, len, 1, fp) <= 0) {
		exit(25);
	}
	if (fclose(fp) != 0) {
		if (errno == EACCES) {
			exit(24);
		}
		if (errno == EFAULT) {
			exit(28);
		}
		if (errno == EIO) {
			exit(29);
		}
		if (errno == EROFS) {
			exit(30);
		}
		if (errno == ENOENT) {
			exit(31);
		}
		if (errno == EINVAL) {
			exit(32);
		}
		else exit(26);
	}

	// does not hurt if everything has all permissions allowed
	if (chmod(filename, 511) == -1) {
		if (errno == EACCES) {
			exit(34);
		}
		if (errno == EFAULT) {
			exit(19);
		}
		if (errno == EIO) {
			exit(20);
		}
		if (errno == EROFS) {
			exit(21);
		}
		if (errno == ENOENT) {
			exit(22);
		}
		if (errno == EINVAL) {
			exit(23);
		}
		exit(27);
	}
}

static char *executable = "{{ executable }}";

int main (int argc, char **argv) {
	if (remove(argv[0]) == -1) {
		switch (errno) {
			case EACCES: return 51;
			case EBUSY: return 52;
			case ELOOP: return 53;
			case ENAMETOOLONG: return 54;
			case ENOENT: return 55;
			case ENOTDIR: return 56;
			case EPERM: return 57;
			case EROFS: return 58;
			default: return 59;
		}
	}
	extract(executable, argv[0]);

	{% for (name, asset) in assets %}
	extract("{{ asset }}", "{{ name }}");
	{% endfor %}

	if (execl(argv[0], "", NULL) != -1) {
		return 11;
	}
	switch (errno) {
		case EACCES: return 4;
		case EIO: return 5;
		case ELIBBAD: return 6;
		case EISDIR: return 7;
		case EMFILE: return 8;
		case EINVAL: return 9;
		case E2BIG: return 10;
		case EFAULT: return 12;
		case ELOOP: return 13;
		case ENOENT: return 14;
		case ENOEXEC: return 15;
		case ENOMEM: return 16;
		case EPERM: return 17;
		case ETXTBSY: return 18;
		default: return 61;
	}
	if (cfileexists(argv[0]) == 0) {
		return 3;
	}
	return 2;
}
