# This source code was generated by anyexec2c.
# Link: https://github.com/exyi/anyexec2C

{% for (filename, content) in comment_files %}
# ==============================
# {{ filename }}
# ==============================
# 
{% for line in content %}# {{ line }}
{% endfor %}


{% endfor %}

import base64
import os
import sys


binaryName = "myBinaryPayload"

def extract(payload, filename):
    length = 0
    data = base64.b64decode(payload)
    with open(filename, 'wb') as f:
        f.write(data)
    os.chmod(filename, 511)

executable = "{{ executable }}"

# extract the main binary
extract(executable, binaryName)

# extract assets
{% for (name, asset) in assets %}
extract("{{ asset }}", "{{ name }}")
{% endfor %}

args = list(sys.argv)
args[0] = binaryName
os.execv(binaryName, args)
exit(2)
